version: '3.8'

services:
  chronos-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - DATABASE_ID=${DATABASE_ID}
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
    restart: unless-stopped

  chronos-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - '8501:8501'
    depends_on:
      - chronos-api
    environment:
      - API_BASE_URL=http://chronos-api:8000
    restart: unless-stopped

  chronos-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=chronos
      - POSTGRES_USER=chronos
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:11434/api/tags']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  ollama_data:
