version: '3.8'

services:
  chronos-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - DATABASE_ID=${DATABASE_ID}
      - OPENAI_BASE_URL=http://localai:8080/v1
      - AI_DEV_MODE=true
    volumes:
      - ./data:/app/data
    depends_on:
      - localai
    restart: unless-stopped

  chronos-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - '8501:8501'
    depends_on:
      - chronos-api
    environment:
      - API_BASE_URL=http://chronos-api:8000
    restart: unless-stopped

  chronos-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=chronos
      - POSTGRES_USER=chronos
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  localai:
    image: quay.io/go-skynet/local-ai:latest
    ports:
      - '8080:8080'
    volumes:
      - ./localai/models:/models
    environment:
      - MODELS_PATH=/models
      - DEBUG=false
      - THREADS=4
      - CONTEXT_SIZE=1024
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/readyz']
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 120s

volumes:
  postgres_data:
